/* 
  This file was generated automatically with /nfs/data-012/marques/software/source/libxc/svn/scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ../maple/lda_x_rel.mpl
  Type of functional: work_lda
*/

static void
func0_lda_x(const xc_func_type *p, xc_lda_work_t *r)
{
  double t1, t2, t4, t5, t7, t8, t9, t10;
  double t11, t16, t25;

  lda_xc_nn_params *params;

  assert(p->params != NULL);
  params = (lda_xc_nn_params * )(p->params);

  t1 = M_CBRT3;
  t2 = t1 * t1;
  t4 = M_CBRT4;
  t5 = params->alpha * t2 * t4;
  t7 = cbrt(0.1e1 / 0.31415926535897932385e1);
  t8 = t7 * t7;
  t9 = M_CBRT2;
  t10 = t9 * t9;
  t11 = t8 * t10;
  r->f = -0.18750000000000000000e0 * t5 * t11 / r->rs;

  if(r->order < 1) return;

  t16 = r->rs * r->rs;
  r->dfdrs = 0.18750000000000000000e0 * t5 * t11 / t16;

  if(r->order < 2) return;

  r->d2fdrs2 = -0.37500000000000000000e0 * t5 * t11 / t16 / r->rs;

  if(r->order < 3) return;

  t25 = t16 * t16;
  r->d3fdrs3 = 0.11250000000000000000e1 * t5 * t11 / t25;

  if(r->order < 4) return;


}

static void
func0_lda_c_pz_mod(const xc_func_type *p, xc_lda_work_t *r)
{
  double t1, t2, t3, t5, t7, t9, t10, t11;
  double t13, t14, t15, t19, t20, t22, t23, t25;
  double t27, t29, t33, t36, t38, t43, t44, t52;
  double t53, t60, t62, t66, t68, t76, t77, t78;
  double t92, t109, t111, t116, t142;

  lda_xc_nn_params *params;

  assert(p->params != NULL);
  params = (lda_xc_nn_params * )(p->params);

  t1 = params->gamma[0];
  t2 = params->beta1[0];
  t3 = sqrt(r->rs);
  t5 = params->beta2[0];
  t7 = t5 * r->rs + t2 * t3 + 0.1e1;
  t9 = t1 / t7;
  t10 = r->rs - 0.1e1;
  t11 = Heaviside(t10);
  t13 = params->c[0];
  t14 = t13 * r->rs;
  t15 = log(r->rs);
  t19 = params->a[0];
  t20 = t19 * t15;
  t22 = params->d[0];
  t23 = t22 * r->rs;
  t25 = params->b[0];
  r->f += -t14 * t15 * t11 - t20 * t11 - t23 * t11 - t25 * t11 + t9 * t11 + t14 * t15 + t20 + t23 + t25; // ADD energy in order to combine energy from two functionals

  if(r->order < 1) return;

  t27 = t7 * t7;
  t29 = t1 / t27;
  t33 = t2 / t3 / 0.2e1 + t5;
  t36 = 0.0;
  t38 = t13 * t15;
  t43 = 0.1e1 / r->rs;
  t44 = t19 * t43;
  r->dfdrs = -t29 * t11 * t33 - t14 * t15 * t36 - t13 * t11 - t22 * t11 - t38 * t11 - t44 * t11 - t20 * t36 - t23 * t36 - t25 * t36 + t9 * t36 + t13 + t22 + t38 + t44;

  if(r->order < 2) return;

  t52 = t1 / t27 / t7;
  t53 = t33 * t33;
  t60 = t11 * t2;
  t62 = 0.1e1 / t3 / r->rs;
  t66 = 0.0;
  t68 = t13 * t43;
  t76 = r->rs * r->rs;
  t77 = 0.1e1 / t76;
  t78 = t19 * t77;
  r->d2fdrs2 = 0.2e1 * t52 * t11 * t53 - 0.2e1 * t29 * t36 * t33 + t29 * t60 * t62 / 0.4e1 + t9 * t66 - t68 * t11 - 0.2e1 * t38 * t36 - 0.2e1 * t13 * t36 - t14 * t15 * t66 + t68 + t78 * t11 - 0.2e1 * t44 * t36 - t20 * t66 - t78 - 0.2e1 * t22 * t36 - t23 * t66 - t25 * t66;

  if(r->order < 3) return;

  t92 = t27 * t27;
  t109 = t13 * t77;
  t111 = 0.0;
  t116 = t19 / t76 / r->rs;
  t142 = -0.3e1 * t38 * t66 + 0.3e1 * t78 * t36 - 0.3e1 * t44 * t66 - t20 * t111 - t23 * t111 - 0.3e1 * t13 * t66 - t109 + 0.2e1 * t116 - 0.3e1 * t22 * t66 - t25 * t111 - 0.3e1 / 0.8e1 * t29 * t60 / t3 / t76;
  r->d3fdrs3 = t142 - 0.3e1 / 0.2e1 * t52 * t11 * t33 * t2 * t62 - 0.6e1 * t1 / t92 * t11 * t53 * t33 + 0.3e1 / 0.4e1 * t29 * t36 * t2 * t62 + 0.6e1 * t52 * t36 * t53 - 0.3e1 * t29 * t66 * t33 + t109 * t11 - t14 * t15 * t111 - 0.2e1 * t116 * t11 + t9 * t111 - 0.3e1 * t68 * t36;

  if(r->order < 4) return;


}

static void
func1(const xc_func_type *p, xc_lda_work_t *r)
{
  double t1, t2, t3, t4, t6, t7, t8, t9;
  double t10, t11, t12, t14, t15, t17, t18, t19;
  double t20, t21, t22, t23, t24, t27, t28, t29;
  double t33, t37, t38, t42, t43, t45, t46, t50;
  double t55, t56, t57, t58, t64, t70, t71, t76;
  double t77, t82, t83, t87, t91, t92, t97, t98;
  double t103, t106, t114, t115, t122, t126, t128, t131;
  double t132, t136, t156, t158, t159, t165, t168;


  t1 = POW_1_3(0.3e1);
  t2 = t1 * t1;
  t3 = POW_1_3(0.4e1);
  t4 = t2 * t3;
  t6 = POW_1_3(0.1e1 / 0.31415926535897932385e1);
  t7 = t6 * t6;
  t8 = t4 * t7;
  t9 = POW_1_3(0.2e1);
  t10 = t9 * t9;
  t11 = 0.1e1 + r->z;
  t12 = POW_1_3(t11);
  t14 = 0.1e1 - r->z;
  t15 = POW_1_3(t14);
  t17 = t12 * t11 + t15 * t14;
  t18 = t10 * t17;
  t19 = 0.1e1 / r->rs;
  t20 = POW_1_3(0.9e1);
  t21 = t20 * t20;
  t22 = t21 * t3;
  t23 = r->rs * r->rs;
  t24 = 0.1e1 / t23;
  t27 = 0.1e1 + 0.28556429993539872704e-4 * t22 * t24;
  t28 = sqrt(t27);
  t29 = t28 * t21;
  t33 = t3 * t3;
  t37 = log(0.26719108327908265315e-2 * t20 * t33 * t19 + sqrt(POW_2(0.26719108327908265315e-2 * t20 * t33 * t19) + 0.1e1));
  t38 = t37 * t20;
  t42 = 0.10396221848752237744e2 * t29 * t3 * r->rs - 0.97273285855626056438e3 * t38 * t33 * t23;
  t43 = t42 * t42;
  t45 = 0.1e1 - 0.15e1 * t43;
  t46 = t19 * t45;
  r->f = -0.3e1 / 0.32e2 * t8 * t18 * t46;

  if(r->order < 1) return;

  t50 = t24 * t45;
  t55 = t4 * t7 * t10;
  t56 = t17 * t19;
  t57 = 0.1e1 / t28;
  t58 = t57 * t20;
  t64 = t57 * t21;
  t70 = -0.26719108327908265315e-2 * t58 * t33 * t24 + 0.10396221848752237744e2 * t29 * t3 + 0.10396221848752237744e2 * t64 * t3 - 0.19454657171125211288e4 * t38 * t33 * r->rs;
  t71 = t42 * t70;
  r->dfdrs = 0.3e1 / 0.32e2 * t8 * t18 * t50 + 0.28125000000000000000e0 * t55 * t56 * t71;
  t76 = 0.4e1 / 0.3e1 * t12 - 0.4e1 / 0.3e1 * t15;
  t77 = t10 * t76;
  r->dfdz = -0.3e1 / 0.32e2 * t8 * t77 * t46;

  if(r->order < 2) return;

  t82 = 0.1e1 / t23 / r->rs;
  t83 = t82 * t45;
  t87 = t17 * t24;
  t91 = t70 * t70;
  t92 = t19 * t91;
  t97 = 0.1e1 / t28 / t27;
  t98 = t23 * t23;
  t103 = t33 * t82;
  t106 = t97 * t20;
  t114 = -0.27468084472405941020e-5 * t97 / t98 / r->rs + 0.26719108327908265315e-2 * t58 * t103 + 0.26719108327908265315e-2 * t106 * t103 + 0.20792443697504475488e2 * t64 * t3 * t19 - 0.19454657171125211288e4 * t38 * t33;
  t115 = t42 * t114;
  r->d2fdrs2 = -0.3e1 / 0.16e2 * t8 * t18 * t83 - 0.56250000000000000000e0 * t55 * t87 * t71 + 0.28125000000000000000e0 * t8 * t18 * t92 + 0.28125000000000000000e0 * t55 * t56 * t115;
  t122 = t76 * t19;
  r->d2fdrsz = 0.3e1 / 0.32e2 * t8 * t77 * t50 + 0.28125000000000000000e0 * t55 * t122 * t71;
  t126 = t12 * t12;
  t128 = t15 * t15;
  t131 = 0.4e1 / 0.9e1 / t126 + 0.4e1 / 0.9e1 / t128;
  t132 = t10 * t131;
  r->d2fdz2 = -0.3e1 / 0.32e2 * t8 * t132 * t46;

  if(r->order < 3) return;

  t136 = 0.1e1 / t98;
  t156 = t27 * t27;
  t158 = 0.1e1 / t28 / t156;
  t159 = t98 * t98;
  t165 = 0.1e1 / t98 / t23;
  t168 = t33 * t136;
  r->d3fdrs3 = 0.9e1 / 0.16e2 * t8 * t18 * t136 * t45 + 0.16875000000000000000e1 * t55 * t17 * t82 * t71 - 0.84375000000000000000e0 * t8 * t18 * t24 * t91 - 0.84375000000000000000e0 * t55 * t87 * t115 + 0.84375000000000000000e0 * t55 * t56 * t70 * t114 + 0.28125000000000000000e0 * t55 * t56 * t42 * (-0.23531712938786995922e-9 * t158 / t159 * t22 + 0.16480850683443564612e-4 * t97 * t165 - 0.80157324983724795945e-2 * t58 * t168 + 0.82404253417217823056e-5 * t158 * t165 - 0.26719108327908265315e-2 * t106 * t168);
  r->d3fdrs2z = -0.3e1 / 0.16e2 * t8 * t77 * t83 - 0.56250000000000000000e0 * t55 * t76 * t24 * t71 + 0.28125000000000000000e0 * t8 * t77 * t92 + 0.28125000000000000000e0 * t55 * t122 * t115;
  r->d3fdrsz2 = 0.3e1 / 0.32e2 * t8 * t132 * t50 + 0.28125000000000000000e0 * t55 * t131 * t19 * t71;
  r->d3fdz3 = -0.3e1 / 0.32e2 * t8 * t10 * (-0.8e1 / 0.27e2 / t126 / t11 + 0.8e1 / 0.27e2 / t128 / t14) * t46;

  if(r->order < 4) return;


}

void 
xc_lda_xc_nn_func(const xc_func_type *p, xc_lda_work_t *r)
{
  if(p->nspin == XC_UNPOLARIZED) {
    func0_lda_x(p, r);
	func0_lda_c_pz_mod(p, r);
  }
  else {
    func1(p, r);
  }
}

#define maple2c_order 3
#define maple2c_func  xc_lda_xc_nn_func
